"""
Second batch of hand-written trivia (history, rivalries, general), with translations.

Each entry: id -> {
    "category": ...,
    "en": (question, correct, [wrong x3], explanation),
    "<lang>": (question, explanation) or (question, explanation, correct, [wrong x3]) when the
             answers are words rather than names/years and need translating too.
}
Only long-settled facts — no current owners, managers or records likely to change soon.
"""

Q2 = {
# --- HISTORY ---
"hist-munich-1958": {"category": "HISTORY",
 "en": ("In which year did the Munich air disaster claim the lives of eight Manchester United players?", "1958", ["1949", "1962", "1966"],
        "The plane carrying the 'Busby Babes' home from a European tie in Belgrade crashed at Munich in February 1958."),
 "de": ("In welchem Jahr kamen beim Flugzeugunglück von München acht Spieler von Manchester United ums Leben?", "Das Flugzeug mit den „Busby Babes“ verunglückte im Februar 1958 in München auf dem Rückweg aus Belgrad."),
 "fr": ("En quelle année la catastrophe aérienne de Munich a-t-elle coûté la vie à huit joueurs de Manchester United ?", "L'avion des « Busby Babes », de retour de Belgrade, s'est écrasé à Munich en février 1958."),
 "nb": ("Hvilket år mistet åtte Manchester United-spillere livet i flyulykken i München?", "Flyet med «Busby Babes» styrtet i München i februar 1958 på vei hjem fra Beograd."),
 "sv": ("Vilket år omkom åtta Manchester United-spelare i flygolyckan i München?", "Planet med ”Busby Babes” störtade i München i februari 1958 på väg hem från Belgrad.")},
"hist-busby": {"category": "HISTORY",
 "en": ("Which manager gave his name to Manchester United's 'Babes' of the 1950s?", "Matt Busby", ["Bill Shankly", "Don Revie", "Brian Clough"],
        "Sir Matt Busby built the young side known as the Busby Babes."),
 "de": ("Nach welchem Trainer wurden die „Babes“ von Manchester United in den 1950ern benannt?", "Sir Matt Busby formte die junge Mannschaft der Busby Babes."),
 "fr": ("Quel entraîneur a donné son nom aux « Babes » de Manchester United dans les années 1950 ?", "Sir Matt Busby a bâti la jeune équipe surnommée les Busby Babes."),
 "nb": ("Hvilken manager ga navn til Manchester Uniteds «Babes» på 1950-tallet?", "Sir Matt Busby bygde det unge laget kjent som Busby Babes."),
 "sv": ("Vilken tränare gav namn åt Manchester Uniteds ”Babes” på 1950-talet?", "Sir Matt Busby byggde det unga laget som kallades Busby Babes.")},
"hist-shankly": {"category": "HISTORY",
 "en": ("Which manager arrived at Liverpool in 1959 and built the club into a powerhouse?", "Bill Shankly", ["Bob Paisley", "Kenny Dalglish", "Joe Fagan"],
        "Bill Shankly took over in December 1959 with Liverpool in the Second Division."),
 "de": ("Welcher Trainer kam 1959 zu Liverpool und machte den Klub zu einer Macht?", "Bill Shankly übernahm im Dezember 1959, als Liverpool in der Second Division spielte."),
 "fr": ("Quel entraîneur est arrivé à Liverpool en 1959 et en a fait une puissance ?", "Bill Shankly a pris les rênes en décembre 1959, alors que Liverpool était en deuxième division."),
 "nb": ("Hvilken manager kom til Liverpool i 1959 og gjorde klubben til en stormakt?", "Bill Shankly tok over i desember 1959, mens Liverpool spilte i Second Division."),
 "sv": ("Vilken tränare kom till Liverpool 1959 och gjorde klubben till en stormakt?", "Bill Shankly tog över i december 1959, när Liverpool spelade i Second Division.")},
"hist-ferguson-titles": {"category": "HISTORY",
 "en": ("How many Premier League titles did Sir Alex Ferguson win with Manchester United?", "13", ["10", "11", "12"],
        "Ferguson won 13 Premier League titles between 1993 and 2013."),
 "de": ("Wie viele Premier-League-Titel gewann Sir Alex Ferguson mit Manchester United?", "Ferguson gewann zwischen 1993 und 2013 13 Premier-League-Titel."),
 "fr": ("Combien de titres de Premier League Sir Alex Ferguson a-t-il remportés avec Manchester United ?", "Ferguson a remporté 13 titres de Premier League entre 1993 et 2013."),
 "nb": ("Hvor mange Premier League-titler vant Sir Alex Ferguson med Manchester United?", "Ferguson vant 13 Premier League-titler mellom 1993 og 2013."),
 "sv": ("Hur många Premier League-titlar vann Sir Alex Ferguson med Manchester United?", "Ferguson vann 13 Premier League-titlar mellan 1993 och 2013.")},
"hist-wenger-years": {"category": "HISTORY",
 "en": ("Arsène Wenger managed Arsenal from 1996 until which year?", "2018", ["2014", "2016", "2019"],
        "Wenger's 22-year spell at Arsenal ended in 2018."),
 "de": ("Arsène Wenger trainierte Arsenal von 1996 bis zu welchem Jahr?", "Wengers 22 Jahre bei Arsenal endeten 2018."),
 "fr": ("Arsène Wenger a entraîné Arsenal de 1996 jusqu'à quelle année ?", "Les 22 ans de Wenger à Arsenal ont pris fin en 2018."),
 "nb": ("Arsène Wenger var manager for Arsenal fra 1996 til hvilket år?", "Wengers 22 år i Arsenal tok slutt i 2018."),
 "sv": ("Arsène Wenger tränade Arsenal från 1996 fram till vilket år?", "Wengers 22 år i Arsenal tog slut 2018.")},
"hist-clough-derby": {"category": "HISTORY",
 "en": ("In which season did Brian Clough win the league title with Derby County?", "1971–72", ["1969–70", "1977–78", "1980–81"],
        "Clough led Derby County to their first league title in 1971–72."),
 "de": ("In welcher Saison gewann Brian Clough mit Derby County die Meisterschaft?", "Clough führte Derby County 1971/72 zur ersten Meisterschaft."),
 "fr": ("Lors de quelle saison Brian Clough a-t-il été champion avec Derby County ?", "Clough a mené Derby County à son premier titre en 1971-72."),
 "nb": ("Hvilken sesong vant Brian Clough ligaen med Derby County?", "Clough ledet Derby County til klubbens første ligatittel i 1971–72."),
 "sv": ("Vilken säsong vann Brian Clough ligan med Derby County?", "Clough ledde Derby County till klubbens första ligatitel 1971–72.")},
"hist-revie": {"category": "HISTORY",
 "en": ("Who managed Leeds United to the league title in 1968–69 and 1973–74?", "Don Revie", ["Howard Wilkinson", "Brian Clough", "Jimmy Armfield"],
        "Don Revie's Leeds were champions in 1968–69 and 1973–74."),
 "de": ("Wer führte Leeds United 1968/69 und 1973/74 zur Meisterschaft?", "Don Revies Leeds wurde 1968/69 und 1973/74 Meister."),
 "fr": ("Qui a mené Leeds United au titre en 1968-69 et 1973-74 ?", "Le Leeds de Don Revie a été champion en 1968-69 et 1973-74."),
 "nb": ("Hvem ledet Leeds United til ligatittelen i 1968–69 og 1973–74?", "Don Revies Leeds ble seriemester i 1968–69 og 1973–74."),
 "sv": ("Vem ledde Leeds United till ligatiteln 1968–69 och 1973–74?", "Don Revies Leeds blev mästare 1968–69 och 1973–74.")},
"hist-last-first-division": {"category": "HISTORY",
 "en": ("Which club won the last First Division title before the Premier League began, in 1991–92?", "Leeds United", ["Manchester United", "Liverpool", "Arsenal"],
        "Leeds finished ahead of Manchester United to win the 1991–92 title."),
 "de": ("Welcher Verein gewann 1991/92 die letzte First Division vor dem Start der Premier League?", "Leeds landete 1991/92 vor Manchester United und wurde Meister."),
 "fr": ("Quel club a remporté le dernier titre de First Division avant la Premier League, en 1991-92 ?", "Leeds a devancé Manchester United pour le titre 1991-92."),
 "nb": ("Hvilken klubb vant den siste First Division-tittelen før Premier League startet, i 1991–92?", "Leeds endte foran Manchester United og vant tittelen 1991–92."),
 "sv": ("Vilken klubb vann den sista First Division-titeln innan Premier League startade, 1991–92?", "Leeds slutade före Manchester United och vann titeln 1991–92.")},
"hist-chelsea-2012": {"category": "HISTORY",
 "en": ("Which English club won the 2012 Champions League final against Bayern Munich on penalties?", "Chelsea", ["Manchester United", "Liverpool", "Arsenal"],
        "Chelsea beat Bayern on penalties in Munich after a 1–1 draw."),
 "de": ("Welcher englische Verein gewann 2012 das Champions-League-Finale gegen Bayern München im Elfmeterschießen?", "Chelsea besiegte Bayern in München nach einem 1:1 im Elfmeterschießen."),
 "fr": ("Quel club anglais a battu le Bayern Munich aux tirs au but en finale de la Ligue des champions 2012 ?", "Chelsea s'est imposé aux tirs au but à Munich après un 1-1."),
 "nb": ("Hvilken engelsk klubb vant Champions League-finalen i 2012 mot Bayern München på straffer?", "Chelsea slo Bayern på straffer i München etter 1–1."),
 "sv": ("Vilken engelsk klubb vann Champions League-finalen 2012 mot Bayern München på straffar?", "Chelsea slog Bayern på straffar i München efter 1–1.")},
"hist-istanbul-2005": {"category": "HISTORY",
 "en": ("Liverpool came back from 3–0 down at half-time to win the 2005 Champions League final against which club?", "AC Milan", ["Juventus", "Real Madrid", "Barcelona"],
        "Liverpool drew 3–3 in Istanbul and won on penalties."),
 "de": ("Gegen welchen Verein holte Liverpool im Champions-League-Finale 2005 ein 0:3 zur Pause auf und gewann?", "Liverpool erkämpfte in Istanbul ein 3:3 und siegte im Elfmeterschießen."),
 "fr": ("Contre quel club Liverpool est-il revenu de 3-0 à la pause pour gagner la finale de la Ligue des champions 2005 ?", "Liverpool a arraché un 3-3 à Istanbul avant de gagner aux tirs au but."),
 "nb": ("Mot hvilken klubb snudde Liverpool 0–3 ved pause til seier i Champions League-finalen i 2005?", "Liverpool kom tilbake til 3–3 i Istanbul og vant på straffer."),
 "sv": ("Mot vilken klubb vände Liverpool 0–3 i halvtid till seger i Champions League-finalen 2005?", "Liverpool kvitterade till 3–3 i Istanbul och vann på straffar.")},
"hist-united-treble": {"category": "HISTORY",
 "en": ("In which season did Manchester United win the Premier League, FA Cup and Champions League treble?", "1998–99", ["1997–98", "1999–2000", "2007–08"],
        "United's treble season ended with two late goals against Bayern Munich in Barcelona."),
 "de": ("In welcher Saison gewann Manchester United das Triple aus Premier League, FA Cup und Champions League?", "Die Triple-Saison endete mit zwei späten Toren gegen Bayern München in Barcelona."),
 "fr": ("Lors de quelle saison Manchester United a-t-il réussi le triplé Premier League, FA Cup et Ligue des champions ?", "La saison du triplé s'est conclue par deux buts tardifs contre le Bayern Munich à Barcelone."),
 "nb": ("Hvilken sesong vant Manchester United trippelen Premier League, FA-cupen og Champions League?", "Trippelsesongen endte med to sene mål mot Bayern München i Barcelona."),
 "sv": ("Vilken säsong vann Manchester United trippeln Premier League, FA-cupen och Champions League?", "Trippelsäsongen avslutades med två sena mål mot Bayern München i Barcelona.")},
"hist-city-treble": {"category": "HISTORY",
 "en": ("In which season did Manchester City win the Premier League, FA Cup and Champions League treble?", "2022–23", ["2020–21", "2021–22", "2023–24"],
        "City beat Inter in Istanbul to complete the treble in 2023."),
 "de": ("In welcher Saison gewann Manchester City das Triple aus Premier League, FA Cup und Champions League?", "City schlug Inter 2023 in Istanbul und machte das Triple perfekt."),
 "fr": ("Lors de quelle saison Manchester City a-t-il réussi le triplé Premier League, FA Cup et Ligue des champions ?", "City a battu l'Inter à Istanbul en 2023 pour compléter le triplé."),
 "nb": ("Hvilken sesong vant Manchester City trippelen Premier League, FA-cupen og Champions League?", "City slo Inter i Istanbul i 2023 og fullførte trippelen."),
 "sv": ("Vilken säsong vann Manchester City trippeln Premier League, FA-cupen och Champions League?", "City slog Inter i Istanbul 2023 och säkrade trippeln.")},
"hist-sunderland-1973": {"category": "HISTORY",
 "en": ("Which Second Division club beat Leeds United in the 1973 FA Cup final?", "Sunderland", ["Fulham", "Middlesbrough", "Sheffield Wednesday"],
        "Ian Porterfield's goal gave Sunderland a famous 1–0 win."),
 "de": ("Welcher Zweitligist schlug Leeds United im FA-Cup-Finale 1973?", "Ian Porterfields Tor bescherte Sunderland einen legendären 1:0-Sieg."),
 "fr": ("Quel club de deuxième division a battu Leeds United en finale de la FA Cup 1973 ?", "Le but d'Ian Porterfield a offert à Sunderland une victoire 1-0 historique."),
 "nb": ("Hvilken klubb fra Second Division slo Leeds United i FA-cupfinalen i 1973?", "Ian Porterfields mål ga Sunderland en berømt 1–0-seier."),
 "sv": ("Vilken klubb från Second Division slog Leeds United i FA-cupfinalen 1973?", "Ian Porterfields mål gav Sunderland en berömd 1–0-seger.")},
"hist-southampton-1976": {"category": "HISTORY",
 "en": ("Second Division Southampton beat which club in the 1976 FA Cup final?", "Manchester United", ["Leeds United", "Liverpool", "Arsenal"],
        "Bobby Stokes scored the only goal at Wembley."),
 "de": ("Gegen welchen Verein gewann Zweitligist Southampton das FA-Cup-Finale 1976?", "Bobby Stokes erzielte in Wembley das einzige Tor."),
 "fr": ("Quel club Southampton, alors en deuxième division, a-t-il battu en finale de la FA Cup 1976 ?", "Bobby Stokes a marqué l'unique but à Wembley."),
 "nb": ("Hvilken klubb slo Southampton, da i Second Division, i FA-cupfinalen i 1976?", "Bobby Stokes scoret kampens eneste mål på Wembley."),
 "sv": ("Vilken klubb slog Southampton, då i Second Division, i FA-cupfinalen 1976?", "Bobby Stokes gjorde matchens enda mål på Wembley.")},
"hist-crazy-gang-1988": {"category": "HISTORY",
 "en": ("Wimbledon's 'Crazy Gang' beat which club in the 1988 FA Cup final?", "Liverpool", ["Everton", "Arsenal", "Tottenham Hotspur"],
        "Lawrie Sanchez scored and Dave Beasant saved a penalty in Wimbledon's 1–0 win."),
 "de": ("Gegen welchen Verein gewann Wimbledons „Crazy Gang“ das FA-Cup-Finale 1988?", "Lawrie Sanchez traf, und Dave Beasant hielt beim 1:0 einen Elfmeter."),
 "fr": ("Quel club le « Crazy Gang » de Wimbledon a-t-il battu en finale de la FA Cup 1988 ?", "Lawrie Sanchez a marqué et Dave Beasant a arrêté un penalty lors du 1-0."),
 "nb": ("Hvilken klubb slo Wimbledons «Crazy Gang» i FA-cupfinalen i 1988?", "Lawrie Sanchez scoret og Dave Beasant reddet et straffespark i 1–0-seieren."),
 "sv": ("Vilken klubb slog Wimbledons ”Crazy Gang” i FA-cupfinalen 1988?", "Lawrie Sanchez gjorde mål och Dave Beasant räddade en straff i 1–0-segern.")},
"hist-white-horse": {"category": "HISTORY",
 "en": ("The first FA Cup final at Wembley, the 1923 'White Horse Final', was won by which club?", "Bolton Wanderers", ["West Ham United", "Newcastle United", "Aston Villa"],
        "Bolton beat West Ham 2–0; a police horse helped clear the crowd from the pitch."),
 "de": ("Welcher Verein gewann 1923 das erste FA-Cup-Finale in Wembley, das „White Horse Final“?", "Bolton schlug West Ham 2:0; ein Polizeipferd half, die Zuschauer vom Platz zu drängen."),
 "fr": ("Quel club a remporté la première finale de FA Cup à Wembley, la « finale du cheval blanc » de 1923 ?", "Bolton a battu West Ham 2-0 ; un cheval de police a aidé à dégager la foule du terrain."),
 "nb": ("Hvilken klubb vant den første FA-cupfinalen på Wembley, «White Horse Final» i 1923?", "Bolton slo West Ham 2–0; en politihest hjalp til med å få publikum av banen."),
 "sv": ("Vilken klubb vann den första FA-cupfinalen på Wembley, ”White Horse Final” 1923?", "Bolton slog West Ham med 2–0; en polishäst hjälpte till att få bort publiken från planen.")},
"hist-ipswich-uefa": {"category": "HISTORY",
 "en": ("Under Bobby Robson, Ipswich Town won which European trophy in 1981?", "UEFA Cup", ["European Cup", "Cup Winners' Cup", "UEFA Super Cup"],
        "Ipswich beat AZ '67 over two legs in the 1981 UEFA Cup final."),
 "de": ("Welchen Europapokal gewann Ipswich Town 1981 unter Bobby Robson?", "Ipswich schlug AZ '67 im Finale 1981 in Hin- und Rückspiel.",
        "UEFA-Pokal", ["Europapokal der Landesmeister", "Europapokal der Pokalsieger", "UEFA-Supercup"]),
 "fr": ("Sous Bobby Robson, quel trophée européen Ipswich Town a-t-il remporté en 1981 ?", "Ipswich a battu l'AZ '67 en finale aller-retour en 1981.",
        "Coupe UEFA", ["Coupe des clubs champions", "Coupe des coupes", "Supercoupe de l'UEFA"]),
 "nb": ("Hvilken europeisk trofé vant Ipswich Town under Bobby Robson i 1981?", "Ipswich slo AZ '67 over to kamper i finalen i 1981.",
        "UEFA-cupen", ["Europacupen", "Cupvinnercupen", "UEFA Super Cup"]),
 "sv": ("Vilken europeisk titel vann Ipswich Town under Bobby Robson 1981?", "Ipswich slog AZ '67 över två matcher i finalen 1981.",
        "Uefacupen", ["Europacupen", "Cupvinnarcupen", "Uefa Super Cup"])},
"hist-villa-1981": {"category": "HISTORY",
 "en": ("Aston Villa won the First Division in which season, the year before their European Cup triumph?", "1980–81", ["1978–79", "1981–82", "1982–83"],
        "Villa were champions in 1980–81 and won the European Cup in 1982."),
 "de": ("In welcher Saison wurde Aston Villa Meister, ein Jahr vor dem Triumph im Europapokal der Landesmeister?", "Villa wurde 1980/81 Meister und gewann 1982 den Europapokal."),
 "fr": ("Lors de quelle saison Aston Villa a-t-il été champion, un an avant de gagner la Coupe des clubs champions ?", "Villa a été champion en 1980-81 puis a gagné la Coupe d'Europe en 1982."),
 "nb": ("Hvilken sesong vant Aston Villa First Division, året før triumfen i Europacupen?", "Villa ble seriemester i 1980–81 og vant Europacupen i 1982."),
 "sv": ("Vilken säsong vann Aston Villa First Division, året före triumfen i Europacupen?", "Villa blev mästare 1980–81 och vann Europacupen 1982.")},
"hist-jack-walker": {"category": "HISTORY",
 "en": ("Whose fortune funded Blackburn Rovers' rise to the 1994–95 Premier League title?", "Jack Walker", ["Roman Abramovich", "Mohamed Al-Fayed", "Sheikh Mansour"],
        "Lifelong fan and steel businessman Jack Walker bankrolled Blackburn's title-winning side."),
 "de": ("Wessen Vermögen finanzierte Blackburn Rovers' Weg zum Premier-League-Titel 1994/95?", "Der Stahlunternehmer und lebenslange Fan Jack Walker finanzierte Blackburns Meisterteam."),
 "fr": ("Quelle fortune a financé l'ascension de Blackburn Rovers jusqu'au titre de Premier League 1994-95 ?", "L'industriel de l'acier et supporter de toujours Jack Walker a financé l'équipe championne."),
 "nb": ("Hvem sin formue finansierte Blackburn Rovers' vei til Premier League-tittelen i 1994–95?", "Stålgründer og livslang supporter Jack Walker finansierte mesterlaget."),
 "sv": ("Vems förmögenhet finansierade Blackburn Rovers väg till Premier League-titeln 1994–95?", "Stålentreprenören och livslånga supportern Jack Walker finansierade mästarlaget.")},
"hist-arsenal-49": {"category": "HISTORY",
 "en": ("How many league games did Arsenal's record unbeaten run last before it ended in October 2004?", "49", ["38", "42", "52"],
        "Manchester United ended the 49-game run at Old Trafford."),
 "de": ("Wie viele Ligaspiele dauerte Arsenals Rekordserie ohne Niederlage, bevor sie im Oktober 2004 endete?", "Manchester United beendete die Serie von 49 Spielen in Old Trafford."),
 "fr": ("Combien de matchs de championnat a duré la série record d'invincibilité d'Arsenal, terminée en octobre 2004 ?", "Manchester United a mis fin à la série de 49 matchs à Old Trafford."),
 "nb": ("Hvor mange ligakamper varte Arsenals rekordrekke uten tap før den tok slutt i oktober 2004?", "Manchester United stoppet rekken på 49 kamper på Old Trafford."),
 "sv": ("Hur många ligamatcher varade Arsenals rekordsvit utan förlust innan den bröts i oktober 2004?", "Manchester United bröt sviten på 49 matcher på Old Trafford.")},
"hist-ranieri": {"category": "HISTORY",
 "en": ("Who managed Leicester City to the 2015–16 Premier League title?", "Claudio Ranieri", ["Nigel Pearson", "Brendan Rodgers", "Craig Shakespeare"],
        "Claudio Ranieri led the 5000–1 outsiders to the title in his first season."),
 "de": ("Wer führte Leicester City 2015/16 zur Premier-League-Meisterschaft?", "Claudio Ranieri führte den 5000:1-Außenseiter in seiner ersten Saison zum Titel."),
 "fr": ("Qui entraînait Leicester City lors du titre de Premier League 2015-16 ?", "Claudio Ranieri a mené l'outsider à 5000 contre 1 au titre dès sa première saison."),
 "nb": ("Hvem ledet Leicester City til Premier League-tittelen i 2015–16?", "Claudio Ranieri ledet outsiderne med odds 5000–1 til tittelen i sin første sesong."),
 "sv": ("Vem ledde Leicester City till Premier League-titeln 2015–16?", "Claudio Ranieri ledde skrällaget med odds 5000–1 till titeln under sin första säsong.")},

# --- RIVALRIES ---
"derby-north-west": {"category": "RIVALRIES",
 "en": ("Which two clubs contest the North West derby?", "Liverpool & Manchester United",
        ["Everton & Manchester City", "Liverpool & Manchester City", "Everton & Manchester United"],
        "The North West derby is Liverpool v Manchester United, England's two most successful clubs."),
 "de": ("Welche zwei Vereine bestreiten das North-West-Derby?", "Das North-West-Derby ist Liverpool gegen Manchester United, Englands zwei erfolgreichste Klubs."),
 "fr": ("Quels clubs disputent le derby du Nord-Ouest ?", "Le derby du Nord-Ouest oppose Liverpool à Manchester United, les deux clubs les plus titrés d'Angleterre."),
 "nb": ("Hvilke to klubber møtes i nordvest-derbyet?", "Nordvest-derbyet er Liverpool mot Manchester United, Englands to mest suksessrike klubber."),
 "sv": ("Vilka två klubbar möts i nordvästderbyt?", "Nordvästderbyt är Liverpool mot Manchester United, Englands två mest framgångsrika klubbar.")},
"derby-west-london": {"category": "RIVALRIES",
 "en": ("Which of Chelsea's West London rivals plays at Craven Cottage?", "Fulham", ["Queens Park Rangers", "Brentford", "Crystal Palace"],
        "Fulham's Craven Cottage is about two miles from Stamford Bridge."),
 "de": ("Welcher West-London-Rivale von Chelsea spielt im Craven Cottage?", "Fulhams Craven Cottage liegt etwa drei Kilometer von der Stamford Bridge entfernt."),
 "fr": ("Lequel des rivaux de Chelsea dans l'ouest de Londres joue à Craven Cottage ?", "Craven Cottage, le stade de Fulham, est à environ trois kilomètres de Stamford Bridge."),
 "nb": ("Hvilken av Chelseas vest-London-rivaler spiller på Craven Cottage?", "Fulhams Craven Cottage ligger rundt tre kilometer fra Stamford Bridge."),
 "sv": ("Vilken av Chelseas rivaler i västra London spelar på Craven Cottage?", "Fulhams Craven Cottage ligger ungefär tre kilometer från Stamford Bridge.")},
"derby-tees-wear": {"category": "RIVALRIES",
 "en": ("Middlesbrough and Sunderland contest which derby?", "Tees–Wear derby", ["Tyne–Wear derby", "Tyne–Tees derby", "Steel City derby"],
        "The Tees–Wear derby is the oldest competitive derby in the North East."),
 "de": ("Welches Derby bestreiten Middlesbrough und Sunderland?", "Das Tees-Wear-Derby ist das älteste Pflichtspielderby im Nordosten."),
 "fr": ("Quel derby oppose Middlesbrough à Sunderland ?", "Le derby Tees-Wear est le plus ancien derby officiel du nord-est."),
 "nb": ("Hvilket derby spiller Middlesbrough og Sunderland?", "Tees–Wear-derbyet er det eldste konkurransederbyet i Nordøst-England."),
 "sv": ("Vilket derby spelar Middlesbrough och Sunderland?", "Tees–Wear-derbyt är det äldsta tävlingsderbyt i nordöstra England.")},
"derby-east-lancashire": {"category": "RIVALRIES",
 "en": ("Which club are Blackburn Rovers' rivals in the East Lancashire derby?", "Burnley", ["Preston North End", "Bolton Wanderers", "Blackpool"],
        "The East Lancashire derby, or Cotton Mills derby, is Blackburn v Burnley."),
 "de": ("Wer ist Blackburn Rovers' Rivale im East-Lancashire-Derby?", "Das East-Lancashire-Derby, auch Cotton-Mills-Derby, ist Blackburn gegen Burnley."),
 "fr": ("Qui est le rival de Blackburn Rovers dans le derby de l'East Lancashire ?", "Le derby de l'East Lancashire, ou derby des filatures, oppose Blackburn à Burnley."),
 "nb": ("Hvem er Blackburn Rovers' rival i East Lancashire-derbyet?", "East Lancashire-derbyet, også kalt Cotton Mills-derbyet, er Blackburn mot Burnley."),
 "sv": ("Vem är Blackburn Rovers rival i East Lancashire-derbyt?", "East Lancashire-derbyt, även kallat Cotton Mills-derbyt, är Blackburn mot Burnley.")},
"derby-devon": {"category": "RIVALRIES",
 "en": ("Plymouth Argyle contest the Devon derby with which club?", "Exeter City", ["Bristol Rovers", "Yeovil Town", "Swindon Town"],
        "Plymouth Argyle v Exeter City is the Devon derby."),
 "de": ("Gegen welchen Verein bestreitet Plymouth Argyle das Devon-Derby?", "Plymouth Argyle gegen Exeter City ist das Devon-Derby."),
 "fr": ("Contre quel club Plymouth Argyle dispute-t-il le derby du Devon ?", "Plymouth Argyle contre Exeter City, c'est le derby du Devon."),
 "nb": ("Mot hvilken klubb spiller Plymouth Argyle Devon-derbyet?", "Plymouth Argyle mot Exeter City er Devon-derbyet."),
 "sv": ("Mot vilken klubb spelar Plymouth Argyle Devonderbyt?", "Plymouth Argyle mot Exeter City är Devonderbyt.")},
"derby-roses": {"category": "RIVALRIES",
 "en": ("The 'Roses rivalry' pits Leeds United against which club?", "Manchester United", ["Liverpool", "Sheffield United", "Chelsea"],
        "It echoes the old Yorkshire–Lancashire rivalry of the Wars of the Roses."),
 "de": ("Gegen welchen Verein tritt Leeds United in der „Roses Rivalry“ an?", "Sie spiegelt die alte Rivalität zwischen Yorkshire und Lancashire aus den Rosenkriegen wider."),
 "fr": ("La « Roses rivalry » oppose Leeds United à quel club ?", "Elle rappelle la vieille rivalité Yorkshire–Lancashire de la guerre des Deux-Roses."),
 "nb": ("«Roses rivalry» setter Leeds United opp mot hvilken klubb?", "Den gjenspeiler den gamle rivaliseringen mellom Yorkshire og Lancashire fra Rosekrigene."),
 "sv": ("”Roses rivalry” ställer Leeds United mot vilken klubb?", "Den speglar den gamla rivaliteten mellan Yorkshire och Lancashire från Rosornas krig.")},
"derby-south-london": {"category": "RIVALRIES",
 "en": ("Crystal Palace v Charlton Athletic is one version of which derby?", "South London derby", ["M23 derby", "North London derby", "West London derby"],
        "Any match between Palace, Charlton, Millwall, AFC Wimbledon and Bromley is a South London derby."),
 "de": ("Crystal Palace gegen Charlton Athletic ist eine Variante welches Derbys?", "Jedes Spiel zwischen Palace, Charlton, Millwall, AFC Wimbledon und Bromley gilt als Süd-London-Derby.",
        "Süd-London-Derby", ["M23-Derby", "Nordlondon-Derby", "West-London-Derby"]),
 "fr": ("Crystal Palace contre Charlton Athletic est une version de quel derby ?", "Tout match entre Palace, Charlton, Millwall, l'AFC Wimbledon et Bromley est un derby du sud de Londres.",
        "Derby du sud de Londres", ["Derby de la M23", "Derby du nord de Londres", "Derby de l'ouest de Londres"]),
 "nb": ("Crystal Palace mot Charlton Athletic er én variant av hvilket derby?", "Alle kamper mellom Palace, Charlton, Millwall, AFC Wimbledon og Bromley er Sør-London-derbyer.",
        "Sør-London-derbyet", ["M23-derbyet", "Nord-London-derbyet", "Vest-London-derbyet"]),
 "sv": ("Crystal Palace mot Charlton Athletic är en variant av vilket derby?", "Alla matcher mellan Palace, Charlton, Millwall, AFC Wimbledon och Bromley räknas som Sydlondonderbyn.",
        "Sydlondonderbyt", ["M23-derbyt", "Nordlondonderbyt", "Västlondonderbyt"])},
"derby-luton-watford": {"category": "RIVALRIES",
 "en": ("Luton Town's fiercest rivals are which Hertfordshire club?", "Watford", ["Stevenage", "Barnet", "Boreham Wood"],
        "Luton and Watford have been rivals since the late 19th century."),
 "de": ("Welcher Verein aus Hertfordshire ist Luton Towns größter Rivale?", "Luton und Watford sind seit dem späten 19. Jahrhundert Rivalen."),
 "fr": ("Quel club du Hertfordshire est le grand rival de Luton Town ?", "Luton et Watford sont rivaux depuis la fin du XIXe siècle."),
 "nb": ("Hvilken klubb fra Hertfordshire er Luton Towns største rival?", "Luton og Watford har vært rivaler siden slutten av 1800-tallet."),
 "sv": ("Vilken klubb från Hertfordshire är Luton Towns största rival?", "Luton och Watford har varit rivaler sedan slutet av 1800-talet.")},
"derby-a420": {"category": "RIVALRIES",
 "en": ("Oxford United's A420 derby is played against which club?", "Swindon Town", ["Reading", "Cheltenham Town", "Bristol Rovers"],
        "The A420 road links Oxford and Swindon."),
 "de": ("Gegen welchen Verein spielt Oxford United das A420-Derby?", "Die Straße A420 verbindet Oxford und Swindon."),
 "fr": ("Contre quel club Oxford United dispute-t-il le derby de l'A420 ?", "La route A420 relie Oxford et Swindon."),
 "nb": ("Mot hvilken klubb spiller Oxford United A420-derbyet?", "Veien A420 forbinder Oxford og Swindon."),
 "sv": ("Mot vilken klubb spelar Oxford United A420-derbyt?", "Vägen A420 förbinder Oxford och Swindon.")},
"derby-cambridgeshire": {"category": "RIVALRIES",
 "en": ("Cambridge United contest the Cambridgeshire derby with which club?", "Peterborough United", ["Luton Town", "Stevenage", "Wycombe Wanderers"],
        "Cambridge United v Peterborough United is the Cambridgeshire derby."),
 "de": ("Gegen welchen Verein bestreitet Cambridge United das Cambridgeshire-Derby?", "Cambridge United gegen Peterborough United ist das Cambridgeshire-Derby."),
 "fr": ("Contre quel club Cambridge United dispute-t-il le derby du Cambridgeshire ?", "Cambridge United contre Peterborough United, c'est le derby du Cambridgeshire."),
 "nb": ("Mot hvilken klubb spiller Cambridge United Cambridgeshire-derbyet?", "Cambridge United mot Peterborough United er Cambridgeshire-derbyet."),
 "sv": ("Mot vilken klubb spelar Cambridge United Cambridgeshirederbyt?", "Cambridge United mot Peterborough United är Cambridgeshirederbyt.")},
"derby-nottingham": {"category": "RIVALRIES",
 "en": ("Which club plays just across the River Trent from Nottingham Forest's City Ground?", "Notts County", ["Derby County", "Mansfield Town", "Leicester City"],
        "Meadow Lane and the City Ground are only a few hundred metres apart."),
 "de": ("Welcher Verein spielt direkt auf der anderen Seite des Trent, gegenüber Nottingham Forests City Ground?", "Meadow Lane und der City Ground liegen nur wenige Hundert Meter auseinander."),
 "fr": ("Quel club joue juste de l'autre côté de la Trent, face au City Ground de Nottingham Forest ?", "Meadow Lane et le City Ground ne sont séparés que de quelques centaines de mètres."),
 "nb": ("Hvilken klubb spiller like over elven Trent fra Nottingham Forests City Ground?", "Meadow Lane og City Ground ligger bare noen hundre meter fra hverandre."),
 "sv": ("Vilken klubb spelar strax på andra sidan floden Trent från Nottingham Forests City Ground?", "Meadow Lane och City Ground ligger bara några hundra meter från varandra.")},
"derby-stanley-park": {"category": "RIVALRIES",
 "en": ("Which park separated Anfield from Everton's old home, Goodison Park?", "Stanley Park", ["Sefton Park", "Hyde Park", "Calderstones Park"],
        "Stanley Park lies between the two grounds, under a mile apart."),
 "de": ("Welcher Park lag zwischen Anfield und Evertons altem Stadion Goodison Park?", "Der Stanley Park liegt zwischen den beiden Stadien, keine zwei Kilometer voneinander entfernt."),
 "fr": ("Quel parc séparait Anfield de l'ancien stade d'Everton, Goodison Park ?", "Stanley Park se trouve entre les deux stades, distants de moins de deux kilomètres."),
 "nb": ("Hvilken park skilte Anfield fra Evertons gamle hjemmebane Goodison Park?", "Stanley Park ligger mellom de to stadionene, under to kilometer fra hverandre."),
 "sv": ("Vilken park skilde Anfield från Evertons gamla hemmaarena Goodison Park?", "Stanley Park ligger mellan de två arenorna, mindre än två kilometer från varandra.")},

# --- GENERAL ---
"gen-promoted-from-championship": {"category": "GENERAL",
 "en": ("How many clubs are promoted from the Championship to the Premier League each season?", "3", ["1", "2", "4"],
        "The top two go up automatically and a third through the play-offs."),
 "de": ("Wie viele Vereine steigen jede Saison aus der Championship in die Premier League auf?", "Die beiden Ersten steigen direkt auf, ein dritter über die Play-offs."),
 "fr": ("Combien de clubs montent chaque saison de Championship en Premier League ?", "Les deux premiers montent directement, un troisième via les play-offs."),
 "nb": ("Hvor mange klubber rykker opp fra Championship til Premier League hver sesong?", "De to øverste rykker opp direkte, og en tredje via playoff."),
 "sv": ("Hur många klubbar flyttas upp från Championship till Premier League varje säsong?", "De två bästa går upp direkt och en tredje via playoff.")},
"gen-relegated-from-pl": {"category": "GENERAL",
 "en": ("How many clubs are relegated from the Premier League each season?", "3", ["2", "4", "5"],
        "The bottom three drop into the Championship."),
 "de": ("Wie viele Vereine steigen jede Saison aus der Premier League ab?", "Die letzten drei steigen in die Championship ab."),
 "fr": ("Combien de clubs sont relégués de Premier League chaque saison ?", "Les trois derniers descendent en Championship."),
 "nb": ("Hvor mange klubber rykker ned fra Premier League hver sesong?", "De tre nederste rykker ned til Championship."),
 "sv": ("Hur många klubbar åker ur Premier League varje säsong?", "De tre sista åker ner till Championship.")},
"gen-championship-playoffs": {"category": "GENERAL",
 "en": ("Which Championship league positions qualify for the play-offs?", "3rd to 6th", ["2nd to 5th", "3rd to 7th", "4th to 7th"],
        "Third to sixth play semi-finals, with the final at Wembley."),
 "de": ("Welche Tabellenplätze der Championship berechtigen zur Teilnahme an den Play-offs?", "Die Plätze drei bis sechs spielen Halbfinals, das Finale findet in Wembley statt.",
        "Platz 3 bis 6", ["Platz 2 bis 5", "Platz 3 bis 7", "Platz 4 bis 7"]),
 "fr": ("Quelles places de Championship qualifient pour les play-offs ?", "Du troisième au sixième, les clubs jouent des demi-finales, avec la finale à Wembley.",
        "De la 3e à la 6e", ["De la 2e à la 5e", "De la 3e à la 7e", "De la 4e à la 7e"]),
 "nb": ("Hvilke tabellplasser i Championship gir playoff-plass?", "Lagene på tredje til sjette plass spiller semifinaler, med finale på Wembley.",
        "3. til 6. plass", ["2. til 5. plass", "3. til 7. plass", "4. til 7. plass"]),
 "sv": ("Vilka tabellplaceringar i Championship ger playoff-plats?", "Lagen på tredje till sjätte plats spelar semifinaler, med final på Wembley.",
        "3:e till 6:e plats", ["2:a till 5:e plats", "3:e till 7:e plats", "4:e till 7:e plats"])},
"gen-national-league-promotion": {"category": "GENERAL",
 "en": ("How many clubs are promoted from the National League to League Two each season?", "2", ["1", "3", "4"],
        "The champions go up automatically, joined by the play-off winners."),
 "de": ("Wie viele Vereine steigen jede Saison aus der National League in die League Two auf?", "Der Meister steigt direkt auf, dazu der Sieger der Play-offs."),
 "fr": ("Combien de clubs montent chaque saison de National League en League Two ?", "Le champion monte directement, accompagné du vainqueur des play-offs."),
 "nb": ("Hvor mange klubber rykker opp fra National League til League Two hver sesong?", "Vinneren rykker opp direkte, sammen med playoff-vinneren."),
 "sv": ("Hur många klubbar flyttas upp från National League till League Two varje säsong?", "Mästarna går upp direkt, tillsammans med playoff-vinnaren.")},
"gen-first-division-name": {"category": "GENERAL",
 "en": ("What was English football's top division called before the Premier League began in 1992?", "First Division", ["Premier Division", "Super League", "Championship"],
        "The Football League First Division was the top flight from 1888 to 1992."),
 "de": ("Wie hieß die höchste englische Liga vor dem Start der Premier League 1992?", "Die First Division der Football League war von 1888 bis 1992 die höchste Liga."),
 "fr": ("Comment s'appelait l'élite du football anglais avant la création de la Premier League en 1992 ?", "La First Division de la Football League a été l'élite de 1888 à 1992."),
 "nb": ("Hva het den øverste divisjonen i engelsk fotball før Premier League startet i 1992?", "Football League First Division var øverste nivå fra 1888 til 1992."),
 "sv": ("Vad hette den högsta divisionen i engelsk fotboll innan Premier League startade 1992?", "Football League First Division var högsta nivån från 1888 till 1992.")},
"gen-community-shield": {"category": "GENERAL",
 "en": ("Which match traditionally opens the English season, between the league champions and the FA Cup winners?", "Community Shield", ["UEFA Super Cup", "EFL Trophy", "Full Members' Cup"],
        "The FA Community Shield is usually played at Wembley in August."),
 "de": ("Welches Spiel eröffnet traditionell die englische Saison, zwischen Meister und FA-Cup-Sieger?", "Der FA Community Shield wird meist im August in Wembley ausgetragen."),
 "fr": ("Quel match ouvre traditionnellement la saison anglaise, entre le champion et le vainqueur de la FA Cup ?", "Le FA Community Shield se joue généralement à Wembley en août."),
 "nb": ("Hvilken kamp åpner tradisjonelt den engelske sesongen, mellom seriemesteren og FA-cupvinneren?", "FA Community Shield spilles vanligvis på Wembley i august."),
 "sv": ("Vilken match inleder traditionellt den engelska säsongen, mellan ligamästaren och FA-cupvinnaren?", "FA Community Shield spelas vanligtvis på Wembley i augusti.")},
"gen-efl-trophy": {"category": "GENERAL",
 "en": ("Which cup competition is mainly for League One and League Two clubs?", "EFL Trophy", ["FA Trophy", "FA Vase", "Community Shield"],
        "The EFL Trophy is played mostly by third- and fourth-tier clubs; the FA Trophy is for non-league sides."),
 "de": ("Welcher Pokalwettbewerb ist vor allem für Vereine aus League One und League Two gedacht?", "Die EFL Trophy spielen vor allem Dritt- und Viertligisten; die FA Trophy ist für Amateurklubs."),
 "fr": ("Quelle coupe est surtout réservée aux clubs de League One et League Two ?", "L'EFL Trophy réunit surtout des clubs des 3e et 4e divisions ; la FA Trophy concerne les clubs non professionnels."),
 "nb": ("Hvilken cupturnering er hovedsakelig for klubber i League One og League Two?", "EFL Trophy spilles mest av klubber på tredje og fjerde nivå; FA Trophy er for klubber utenfor ligasystemet."),
 "sv": ("Vilken cupturnering är främst för klubbar i League One och League Two?", "EFL Trophy spelas mest av klubbar på tredje och fjärde nivån; FA Trophy är för klubbar utanför ligasystemet.")},
"gen-world-cup-1966": {"category": "GENERAL",
 "en": ("In which year did England win the World Cup?", "1966", ["1962", "1970", "1974"],
        "England beat West Germany 4–2 after extra time at Wembley."),
 "de": ("In welchem Jahr wurde England Weltmeister?", "England schlug Westdeutschland in Wembley nach Verlängerung 4:2."),
 "fr": ("En quelle année l'Angleterre a-t-elle remporté la Coupe du monde ?", "L'Angleterre a battu la RFA 4-2 après prolongation à Wembley."),
 "nb": ("Hvilket år vant England VM?", "England slo Vest-Tyskland 4–2 etter ekstraomganger på Wembley."),
 "sv": ("Vilket år vann England VM?", "England slog Västtyskland med 4–2 efter förlängning på Wembley.")},
"gen-hurst-hat-trick": {"category": "GENERAL",
 "en": ("Who scored a hat-trick in the 1966 World Cup final?", "Geoff Hurst", ["Bobby Charlton", "Jimmy Greaves", "Martin Peters"],
        "Geoff Hurst scored three times; Martin Peters got England's other goal."),
 "de": ("Wer erzielte im WM-Finale 1966 einen Hattrick?", "Geoff Hurst traf dreimal; Martin Peters erzielte das andere englische Tor."),
 "fr": ("Qui a réussi un triplé en finale de la Coupe du monde 1966 ?", "Geoff Hurst a marqué trois fois ; Martin Peters a inscrit l'autre but anglais."),
 "nb": ("Hvem scoret hattrick i VM-finalen i 1966?", "Geoff Hurst scoret tre ganger; Martin Peters scoret Englands andre mål."),
 "sv": ("Vem gjorde hattrick i VM-finalen 1966?", "Geoff Hurst gjorde tre mål; Martin Peters gjorde Englands andra mål.")},
"gen-var": {"category": "GENERAL",
 "en": ("In which season was VAR introduced in the Premier League?", "2019–20", ["2017–18", "2018–19", "2020–21"],
        "VAR was used in the Premier League for the first time in August 2019."),
 "de": ("In welcher Saison wurde der VAR in der Premier League eingeführt?", "Der VAR kam in der Premier League erstmals im August 2019 zum Einsatz."),
 "fr": ("Lors de quelle saison la VAR a-t-elle été introduite en Premier League ?", "La VAR a été utilisée pour la première fois en Premier League en août 2019."),
 "nb": ("Hvilken sesong ble VAR innført i Premier League?", "VAR ble brukt i Premier League for første gang i august 2019."),
 "sv": ("Vilken säsong infördes VAR i Premier League?", "VAR användes i Premier League för första gången i augusti 2019.")},
"gen-boxing-day": {"category": "GENERAL",
 "en": ("On which date is the traditional Boxing Day programme of English football played?", "26 December", ["24 December", "25 December", "27 December"],
        "Boxing Day, 26 December, is one of the busiest days of the English football calendar."),
 "de": ("An welchem Datum findet der traditionelle Boxing-Day-Spieltag im englischen Fußball statt?", "Am Boxing Day, dem 26. Dezember, ist im englischen Fußball besonders viel los.",
        "26. Dezember", ["24. Dezember", "25. Dezember", "27. Dezember"]),
 "fr": ("À quelle date se joue la traditionnelle journée du Boxing Day en Angleterre ?", "Le Boxing Day, le 26 décembre, est l'un des jours les plus chargés du football anglais.",
        "26 décembre", ["24 décembre", "25 décembre", "27 décembre"]),
 "nb": ("Hvilken dato spilles den tradisjonelle Boxing Day-runden i engelsk fotball?", "Boxing Day, 26. desember, er en av de travleste dagene i engelsk fotball.",
        "26. desember", ["24. desember", "25. desember", "27. desember"]),
 "sv": ("Vilket datum spelas den traditionella Boxing Day-omgången i engelsk fotboll?", "Boxing Day, den 26 december, är en av de mest intensiva dagarna i engelsk fotboll.",
        "26 december", ["24 december", "25 december", "27 december"])},
"gen-golden-glove": {"category": "GENERAL",
 "en": ("Which Premier League award goes to the goalkeeper with the most clean sheets?", "Golden Glove", ["Golden Boot", "Golden Ball", "Silver Boot"],
        "The Golden Boot goes to the top scorer; the Golden Glove to the keeper with the most clean sheets."),
 "de": ("Welche Premier-League-Auszeichnung erhält der Torwart mit den meisten Spielen ohne Gegentor?", "Der Golden Boot geht an den besten Torschützen, der Golden Glove an den Torwart mit den meisten Weißen Westen."),
 "fr": ("Quelle récompense de Premier League va au gardien ayant le plus de clean sheets ?", "Le Golden Boot récompense le meilleur buteur, le Golden Glove le gardien avec le plus de clean sheets."),
 "nb": ("Hvilken Premier League-pris går til keeperen med flest kamper uten baklengsmål?", "Golden Boot går til toppscoreren, Golden Glove til keeperen med flest kamper uten baklengsmål."),
 "sv": ("Vilket Premier League-pris går till målvakten med flest hållna nollor?", "Golden Boot går till skyttekungen, Golden Glove till målvakten med flest hållna nollor.")},
"gen-fa-founded": {"category": "GENERAL",
 "en": ("In which year was the Football Association (FA) founded?", "1863", ["1855", "1871", "1888"],
        "The FA was formed in a London tavern in 1863 and wrote the first agreed rules."),
 "de": ("In welchem Jahr wurde die Football Association (FA) gegründet?", "Die FA entstand 1863 in einem Londoner Pub und schrieb die ersten gemeinsamen Regeln."),
 "fr": ("En quelle année la Football Association (FA) a-t-elle été fondée ?", "La FA est née en 1863 dans une taverne londonienne et a rédigé les premières règles communes."),
 "nb": ("Hvilket år ble The Football Association (FA) stiftet?", "FA ble stiftet på en London-pub i 1863 og skrev de første felles reglene."),
 "sv": ("Vilket år grundades The Football Association (FA)?", "FA bildades på en pub i London 1863 och skrev de första gemensamma reglerna.")},
"gen-sheffield-fc": {"category": "GENERAL",
 "en": ("Sheffield FC, founded in 1857, is recognised by FIFA as the world's oldest what?", "Football club", ["Football stadium", "Football league", "Cup competition"],
        "Sheffield FC still plays in the lower levels of the English pyramid."),
 "de": ("Sheffield FC, gegründet 1857, gilt bei der FIFA als ältester … der Welt?", "Sheffield FC spielt heute noch in den unteren Ligen der englischen Pyramide.",
        "Fußballverein", ["Fußballstadion", "Fußballliga", "Pokalwettbewerb"]),
 "fr": ("Le Sheffield FC, fondé en 1857, est reconnu par la FIFA comme le plus ancien… du monde ?", "Le Sheffield FC joue toujours dans les divisions inférieures anglaises.",
        "Club de football", ["Stade de football", "Championnat de football", "Coupe"]),
 "nb": ("Sheffield FC, stiftet i 1857, er anerkjent av FIFA som verdens eldste hva?", "Sheffield FC spiller fortsatt på de lavere nivåene i den engelske pyramiden.",
        "Fotballklubb", ["Fotballstadion", "Fotball-liga", "Cupturnering"]),
 "sv": ("Sheffield FC, grundad 1857, är erkänd av Fifa som världens äldsta vad?", "Sheffield FC spelar fortfarande på de lägre nivåerna i den engelska pyramiden.",
        "Fotbollsklubb", ["Fotbollsarena", "Fotbollsliga", "Cupturnering"])},
"gen-pl-games-per-season": {"category": "GENERAL",
 "en": ("How many league matches does each Premier League club play in a season?", "38", ["34", "42", "46"],
        "20 clubs play each other home and away: 38 games."),
 "de": ("Wie viele Ligaspiele bestreitet jeder Premier-League-Verein pro Saison?", "20 Vereine spielen in Hin- und Rückspiel gegeneinander: 38 Spiele."),
 "fr": ("Combien de matchs de championnat chaque club de Premier League joue-t-il par saison ?", "20 clubs s'affrontent en aller-retour : 38 matchs."),
 "nb": ("Hvor mange ligakamper spiller hver Premier League-klubb i løpet av en sesong?", "20 klubber møtes hjemme og borte: 38 kamper."),
 "sv": ("Hur många ligamatcher spelar varje Premier League-klubb under en säsong?", "20 klubbar möts hemma och borta: 38 matcher.")},
"gen-efl-games-per-season": {"category": "GENERAL",
 "en": ("How many league matches does each Championship club play in a season?", "46", ["38", "42", "44"],
        "24 clubs play each other home and away: 46 games."),
 "de": ("Wie viele Ligaspiele bestreitet jeder Championship-Verein pro Saison?", "24 Vereine spielen in Hin- und Rückspiel gegeneinander: 46 Spiele."),
 "fr": ("Combien de matchs de championnat chaque club de Championship joue-t-il par saison ?", "24 clubs s'affrontent en aller-retour : 46 matchs."),
 "nb": ("Hvor mange ligakamper spiller hver Championship-klubb i løpet av en sesong?", "24 klubber møtes hjemme og borte: 46 kamper."),
 "sv": ("Hur många ligamatcher spelar varje Championship-klubb under en säsong?", "24 klubbar möts hemma och borta: 46 matcher.")},
}
