"""Hand-written trivia questions (English originals), published in docs/data/deltas_v{N}.json."""

# (id, category, question, correct, [wrong x3], explanation)
Q = [
    # --- RIVALRIES ---
    ("derby-tyne-wear", "RIVALRIES", "Which two clubs contest the Tyne–Wear derby?", "Newcastle United & Sunderland",
     ["Newcastle United & Middlesbrough", "Sunderland & Hartlepool United", "Middlesbrough & Sunderland"],
     "The Tyne–Wear derby is between Newcastle United and Sunderland."),
    ("derby-north-london", "RIVALRIES", "Who are Arsenal's rivals in the North London derby?", "Tottenham Hotspur",
     ["Chelsea", "West Ham United", "Fulham"], "Arsenal and Tottenham Hotspur contest the North London derby."),
    ("derby-merseyside", "RIVALRIES", "Which two clubs contest the Merseyside derby?", "Liverpool & Everton",
     ["Liverpool & Tranmere Rovers", "Everton & Tranmere Rovers", "Liverpool & Manchester United"],
     "The Merseyside derby is between Liverpool and Everton."),
    ("derby-second-city", "RIVALRIES", "Which club are Aston Villa's rivals in the Second City derby?", "Birmingham City",
     ["West Bromwich Albion", "Wolverhampton Wanderers", "Coventry City"],
     "The Second City derby is Aston Villa v Birmingham City."),
    ("derby-steel-city", "RIVALRIES", "The Steel City derby is played between which two clubs?",
     "Sheffield United & Sheffield Wednesday",
     ["Sheffield Wednesday & Rotherham United", "Sheffield United & Barnsley", "Barnsley & Rotherham United"],
     "The Steel City derby is between Sheffield United and Sheffield Wednesday."),
    ("derby-south-coast", "RIVALRIES", "Who are Southampton's rivals in the South Coast derby?", "Portsmouth",
     ["AFC Bournemouth", "Brighton & Hove Albion", "Reading"],
     "The South Coast derby is Southampton v Portsmouth."),
    ("derby-east-anglian", "RIVALRIES", "Which two clubs contest the East Anglian derby?", "Ipswich Town & Norwich City",
     ["Ipswich Town & Colchester United", "Norwich City & Cambridge United", "Colchester United & Cambridge United"],
     "The East Anglian derby is between Ipswich Town and Norwich City."),
    ("derby-black-country", "RIVALRIES", "Which club are Wolves' rivals in the Black Country derby?", "West Bromwich Albion",
     ["Walsall", "Aston Villa", "Birmingham City"],
     "The Black Country derby is Wolverhampton Wanderers v West Bromwich Albion."),
    ("derby-m23", "RIVALRIES", "Brighton & Hove Albion's M23 derby rivals are…", "Crystal Palace",
     ["Crawley Town", "Fulham", "Southampton"], "Brighton and Crystal Palace contest the M23 derby."),
    ("derby-south-wales", "RIVALRIES", "Which two clubs contest the South Wales derby?", "Cardiff City & Swansea City",
     ["Cardiff City & Newport County", "Swansea City & Newport County", "Cardiff City & Wrexham"],
     "The South Wales derby is between Cardiff City and Swansea City."),
    ("derby-east-midlands", "RIVALRIES", "Which club are Derby County's fiercest East Midlands rivals?", "Nottingham Forest",
     ["Leicester City", "Notts County", "Mansfield Town"],
     "Derby County and Nottingham Forest contest the East Midlands derby, also linked by the Brian Clough Trophy."),
    ("derby-bristol", "RIVALRIES", "Who are Bristol City's local rivals in the Bristol derby?", "Bristol Rovers",
     ["Cardiff City", "Swindon Town", "Cheltenham Town"], "The Bristol derby is Bristol City v Bristol Rovers."),
    ("derby-potteries", "RIVALRIES", "Which two clubs contest the Potteries derby?", "Stoke City & Port Vale",
     ["Stoke City & Crewe Alexandra", "Port Vale & Crewe Alexandra", "Stoke City & Walsall"],
     "The Potteries derby is between Stoke City and Port Vale, both from Stoke-on-Trent."),
    ("derby-manchester", "RIVALRIES", "Which two clubs contest the Manchester derby?", "Manchester City & Manchester United",
     ["Manchester United & Salford City", "Manchester City & Stockport County", "Manchester United & Bolton Wanderers"],
     "The Manchester derby is City v United."),
    ("derby-dockers", "RIVALRIES", "Millwall's fiercest rivalry, rooted in London's docks, is with which club?", "West Ham United",
     ["Charlton Athletic", "Crystal Palace", "Leyton Orient"],
     "Millwall v West Ham is often called the Dockers' derby."),
    ("derby-severnside", "RIVALRIES", "The Severnside derby is played between Bristol City and which club?", "Cardiff City",
     ["Swansea City", "Plymouth Argyle", "Cheltenham Town"],
     "Bristol City and Cardiff City, either side of the Severn estuary, contest the Severnside derby."),

    # --- HISTORY ---
    ("hist-oldest-professional", "HISTORY", "Which club, founded in 1862, is often called the oldest professional football club in the world?",
     "Notts County", ["Stoke City", "Nottingham Forest", "Sheffield Wednesday"],
     "Notts County were founded in 1862."),
    ("hist-first-english-european-cup", "HISTORY", "Which was the first English club to win the European Cup, in 1968?",
     "Manchester United", ["Liverpool", "Tottenham Hotspur", "Leeds United"],
     "Manchester United beat Benfica 4–1 at Wembley in 1968."),
    ("hist-invincibles", "HISTORY", "Which club went the whole 2003–04 Premier League season unbeaten?", "Arsenal",
     ["Chelsea", "Manchester United", "Liverpool"], "Arsenal's 'Invincibles' won 26 and drew 12 in 2003–04."),
    ("hist-first-pl-champions", "HISTORY", "Who won the first Premier League title, in 1992–93?", "Manchester United",
     ["Aston Villa", "Blackburn Rovers", "Leeds United"], "Manchester United won the inaugural Premier League, ahead of Aston Villa."),
    ("hist-leicester-title", "HISTORY", "In which season did Leicester City win the Premier League as 5000–1 outsiders?", "2015–16",
     ["2014–15", "2016–17", "2013–14"], "Leicester City were crowned champions in 2015–16."),
    ("hist-blackburn-title", "HISTORY", "Which club won the Premier League in 1994–95?", "Blackburn Rovers",
     ["Manchester United", "Newcastle United", "Liverpool"], "Blackburn Rovers pipped Manchester United to the 1994–95 title."),
    ("hist-forest-european-cups", "HISTORY", "Which club won the European Cup in both 1979 and 1980?", "Nottingham Forest",
     ["Liverpool", "Aston Villa", "Leeds United"], "Brian Clough's Nottingham Forest won back-to-back European Cups."),
    ("hist-villa-european-cup", "HISTORY", "In which year did Aston Villa win the European Cup?", "1982",
     ["1979", "1984", "1977"], "Aston Villa beat Bayern Munich 1–0 in Rotterdam in 1982."),
    ("hist-preston-invincibles", "HISTORY", "Which club were the first Football League champions, unbeaten in 1888–89?", "Preston North End",
     ["Aston Villa", "Everton", "Blackburn Rovers"], "Preston North End won the league unbeaten and the FA Cup in 1888–89."),
    ("hist-highbury", "HISTORY", "Which club played at Highbury until 2006?", "Arsenal",
     ["Tottenham Hotspur", "Chelsea", "Queens Park Rangers"], "Arsenal left Highbury for the Emirates Stadium in 2006."),
    ("hist-maine-road", "HISTORY", "Which club played at Maine Road until 2003?", "Manchester City",
     ["Manchester United", "Stockport County", "Bolton Wanderers"], "Manchester City moved from Maine Road to the City of Manchester Stadium in 2003."),
    ("hist-upton-park", "HISTORY", "Which club left the Boleyn Ground (Upton Park) in 2016?", "West Ham United",
     ["Millwall", "Charlton Athletic", "Leyton Orient"], "West Ham moved to the London Stadium in 2016."),
    ("hist-ayresome-park", "HISTORY", "Which club played at Ayresome Park before moving to the Riverside Stadium in 1995?", "Middlesbrough",
     ["Sunderland", "Hartlepool United", "Newcastle United"], "Middlesbrough left Ayresome Park in 1995."),
    ("hist-roker-park", "HISTORY", "Which club played at Roker Park until 1997?", "Sunderland",
     ["Newcastle United", "Middlesbrough", "Gateshead"], "Sunderland moved from Roker Park to the Stadium of Light in 1997."),
    ("hist-newton-heath", "HISTORY", "Which club was originally called Newton Heath?", "Manchester United",
     ["Manchester City", "Bolton Wanderers", "Oldham Athletic"], "Newton Heath became Manchester United in 1902."),
    ("hist-thames-ironworks", "HISTORY", "Which club was founded as Thames Ironworks?", "West Ham United",
     ["Millwall", "Charlton Athletic", "Arsenal"], "Thames Ironworks F.C. became West Ham United in 1900."),
    ("hist-small-heath", "HISTORY", "Which club was once known as Small Heath?", "Birmingham City",
     ["Aston Villa", "West Bromwich Albion", "Wolverhampton Wanderers"], "Small Heath became Birmingham, then Birmingham City."),
    ("hist-dial-square", "HISTORY", "Which club began life as Dial Square in 1886?", "Arsenal",
     ["Tottenham Hotspur", "Fulham", "Chelsea"], "Dial Square became Royal Arsenal, then Woolwich Arsenal, then Arsenal."),
    ("hist-wigan-2013", "HISTORY", "Which club won the 2013 FA Cup and were relegated from the Premier League in the same season?",
     "Wigan Athletic", ["Portsmouth", "Birmingham City", "Cardiff City"], "Wigan beat Manchester City 1–0 in the final, then went down days later."),
    ("hist-portsmouth-2008", "HISTORY", "Which club beat Cardiff City in the 2008 FA Cup final?", "Portsmouth",
     ["Southampton", "Middlesbrough", "Barnsley"], "Portsmouth won 1–0 with a Kanu goal."),

    # --- GENERAL ---
    ("gen-pl-size", "GENERAL", "How many clubs play in the Premier League?", "20", ["18", "22", "24"],
     "The Premier League has had 20 clubs since 1995–96."),
    ("gen-efl-size", "GENERAL", "How many clubs are in each of the Championship, League One and League Two?", "24",
     ["20", "22", "26"], "Each EFL division has 24 clubs."),
    ("gen-national-league-tier", "GENERAL", "Which tier of the English football pyramid is the National League?", "Fifth",
     ["Fourth", "Sixth", "Third"], "The National League sits directly below League Two, as tier five."),
    ("gen-playoff-venue", "GENERAL", "Where are the EFL play-off finals played?", "Wembley Stadium",
     ["Villa Park", "Old Trafford", "Millennium Stadium"], "The play-off finals are held at Wembley."),
    ("gen-three-points", "GENERAL", "Since 1981, how many points does a league win earn in English football?", "3",
     ["2", "4", "1"], "England switched from two to three points for a win in 1981."),
    ("gen-football-league-founded", "GENERAL", "In which year was the Football League founded?", "1888",
     ["1863", "1872", "1892"], "The Football League kicked off in 1888 with 12 clubs."),
    ("gen-premier-league-founded", "GENERAL", "In which year did the Premier League begin?", "1992",
     ["1990", "1994", "1988"], "The Premier League's first season was 1992–93."),
    ("gen-fa-cup-first", "GENERAL", "The FA Cup, the oldest national football competition, was first played in which season?", "1871–72",
     ["1888–89", "1863–64", "1901–02"], "Wanderers won the first FA Cup in 1872."),
    ("gen-wrexham-owners", "GENERAL", "Which club was bought by actors Ryan Reynolds and Rob McElhenney in 2021?", "Wrexham",
     ["Salford City", "Bromley", "Notts County"], "The takeover of Wrexham was completed in February 2021."),
]


def questions():
    out = []
    for qid, cat, text, correct, wrong, expl in Q:
        assert len(wrong) == 3 and correct not in wrong and len(set(wrong)) == 3, qid
        out.append({"id": qid, "questionText": text, "category": cat, "correctAnswer": correct,
                    "wrongAnswers": wrong, "explanation": expl, "imageUriOrUrl": None, "version": 1})
    assert len({q["id"] for q in out}) == len(out)
    return out


if __name__ == "__main__":
    qs = questions()
    print(len(qs), {c: sum(q["category"] == c for q in qs) for c in ("RIVALRIES", "HISTORY", "GENERAL")})
